[project]
name = "k617-ctrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "microgod", email = "ayoubdya@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dpkt>=1.9.8",
    "hidapi>=0.15.0",
]

[project.scripts]
k617-ctrl = "k617_ctrl:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
